os: osx 
language: swift
osx_image: xcode11.6
xcode_workspace: VCR.xcworkspace
xcode_scheme: VCR_Tests
xcode_destination: platform=iOS Simulator,OS=13.4,name=iPhone X
cache: cocoapods

before_install:
  - cd Example
  - pod repo update
